name: Django CI and Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Installer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Tester l'application (optionnel)
    - name: Run tests
      run: |
        python manage.py test

    # Construire l'image Docker
    - name: Build Docker image
      run: docker build -t django-app .

    # Déployer sur Render
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.dpg-d4jeebeuk2gs73bj5epg-a }}
        api-key: ${{ secrets.djangoo }}
